# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unittest_no_arena_lite.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unittest_no_arena_lite.proto',
  package='protobuf_unittest_no_arena',
  syntax='proto2',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x1cunittest_no_arena_lite.proto\x12\x1aprotobuf_unittest_no_arena\"\x1f\n\x12\x46oreignMessageLite\x12\t\n\x01\x63\x18\x01 \x01(\x05\x42\x02H\x03')
)




_FOREIGNMESSAGELITE = _descriptor.Descriptor(
  name='ForeignMessageLite',
  full_name='protobuf_unittest_no_arena.ForeignMessageLite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c', full_name='protobuf_unittest_no_arena.ForeignMessageLite.c', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['ForeignMessageLite'] = _FOREIGNMESSAGELITE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForeignMessageLite = _reflection.GeneratedProtocolMessageType('ForeignMessageLite', (_message.Message,), {
  'DESCRIPTOR' : _FOREIGNMESSAGELITE,
  '__module__' : 'unittest_no_arena_lite_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_unittest_no_arena.ForeignMessageLite)
  })
_sym_db.RegisterMessage(ForeignMessageLite)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
