# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unittest_drop_unknown_fields.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unittest_drop_unknown_fields.proto',
  package='unittest_drop_unknown_fields',
  syntax='proto3',
  serialized_options=_b('\242\002\014DropUnknowns\252\002\032Google.Protobuf.TestProtos'),
  serialized_pb=_b('\n\"unittest_drop_unknown_fields.proto\x12\x1cunittest_drop_unknown_fields\"\x85\x01\n\x03\x46oo\x12\x13\n\x0bint32_value\x18\x01 \x01(\x05\x12@\n\nenum_value\x18\x02 \x01(\x0e\x32,.unittest_drop_unknown_fields.Foo.NestedEnum\"\'\n\nNestedEnum\x12\x07\n\x03\x46OO\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\"\xc7\x01\n\x12\x46ooWithExtraFields\x12\x13\n\x0bint32_value\x18\x01 \x01(\x05\x12O\n\nenum_value\x18\x02 \x01(\x0e\x32;.unittest_drop_unknown_fields.FooWithExtraFields.NestedEnum\x12\x19\n\x11\x65xtra_int32_value\x18\x03 \x01(\x05\"0\n\nNestedEnum\x12\x07\n\x03\x46OO\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\x12\x07\n\x03QUX\x10\x03\x42,\xa2\x02\x0c\x44ropUnknowns\xaa\x02\x1aGoogle.Protobuf.TestProtosb\x06proto3')
)



_FOO_NESTEDENUM = _descriptor.EnumDescriptor(
  name='NestedEnum',
  full_name='unittest_drop_unknown_fields.Foo.NestedEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAZ', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=163,
  serialized_end=202,
)
_sym_db.RegisterEnumDescriptor(_FOO_NESTEDENUM)

_FOOWITHEXTRAFIELDS_NESTEDENUM = _descriptor.EnumDescriptor(
  name='NestedEnum',
  full_name='unittest_drop_unknown_fields.FooWithExtraFields.NestedEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAZ', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUX', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=356,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_FOOWITHEXTRAFIELDS_NESTEDENUM)


_FOO = _descriptor.Descriptor(
  name='Foo',
  full_name='unittest_drop_unknown_fields.Foo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_value', full_name='unittest_drop_unknown_fields.Foo.int32_value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum_value', full_name='unittest_drop_unknown_fields.Foo.enum_value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FOO_NESTEDENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=202,
)


_FOOWITHEXTRAFIELDS = _descriptor.Descriptor(
  name='FooWithExtraFields',
  full_name='unittest_drop_unknown_fields.FooWithExtraFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_value', full_name='unittest_drop_unknown_fields.FooWithExtraFields.int32_value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum_value', full_name='unittest_drop_unknown_fields.FooWithExtraFields.enum_value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_int32_value', full_name='unittest_drop_unknown_fields.FooWithExtraFields.extra_int32_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FOOWITHEXTRAFIELDS_NESTEDENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=404,
)

_FOO.fields_by_name['enum_value'].enum_type = _FOO_NESTEDENUM
_FOO_NESTEDENUM.containing_type = _FOO
_FOOWITHEXTRAFIELDS.fields_by_name['enum_value'].enum_type = _FOOWITHEXTRAFIELDS_NESTEDENUM
_FOOWITHEXTRAFIELDS_NESTEDENUM.containing_type = _FOOWITHEXTRAFIELDS
DESCRIPTOR.message_types_by_name['Foo'] = _FOO
DESCRIPTOR.message_types_by_name['FooWithExtraFields'] = _FOOWITHEXTRAFIELDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Foo = _reflection.GeneratedProtocolMessageType('Foo', (_message.Message,), {
  'DESCRIPTOR' : _FOO,
  '__module__' : 'unittest_drop_unknown_fields_pb2'
  # @@protoc_insertion_point(class_scope:unittest_drop_unknown_fields.Foo)
  })
_sym_db.RegisterMessage(Foo)

FooWithExtraFields = _reflection.GeneratedProtocolMessageType('FooWithExtraFields', (_message.Message,), {
  'DESCRIPTOR' : _FOOWITHEXTRAFIELDS,
  '__module__' : 'unittest_drop_unknown_fields_pb2'
  # @@protoc_insertion_point(class_scope:unittest_drop_unknown_fields.FooWithExtraFields)
  })
_sym_db.RegisterMessage(FooWithExtraFields)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
