# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InventoryMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Struct import ItemStruct_pb2 as Struct_dot_ItemStruct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='InventoryMessage.proto',
  package='InventoryMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16InventoryMessage.proto\x12\x10InventoryMessage\x1a\x17Struct/ItemStruct.proto\"*\n\x08ItemInfo\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"b\n\x0c\x42\x61\x63kpackInfo\x12\'\n\titem_type\x18\x01 \x01(\x0e\x32\x14.ItemStruct.ItemType\x12)\n\x05items\x18\x02 \x03(\x0b\x32\x1a.InventoryMessage.ItemInfob\x06proto3')
  ,
  dependencies=[Struct_dot_ItemStruct__pb2.DESCRIPTOR,])




_ITEMINFO = _descriptor.Descriptor(
  name='ItemInfo',
  full_name='InventoryMessage.ItemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='InventoryMessage.ItemInfo.item_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='InventoryMessage.ItemInfo.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=111,
)


_BACKPACKINFO = _descriptor.Descriptor(
  name='BackpackInfo',
  full_name='InventoryMessage.BackpackInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_type', full_name='InventoryMessage.BackpackInfo.item_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='InventoryMessage.BackpackInfo.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=211,
)

_BACKPACKINFO.fields_by_name['item_type'].enum_type = Struct_dot_ItemStruct__pb2._ITEMTYPE
_BACKPACKINFO.fields_by_name['items'].message_type = _ITEMINFO
DESCRIPTOR.message_types_by_name['ItemInfo'] = _ITEMINFO
DESCRIPTOR.message_types_by_name['BackpackInfo'] = _BACKPACKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemInfo = _reflection.GeneratedProtocolMessageType('ItemInfo', (_message.Message,), {
  'DESCRIPTOR' : _ITEMINFO,
  '__module__' : 'InventoryMessage_pb2'
  # @@protoc_insertion_point(class_scope:InventoryMessage.ItemInfo)
  })
_sym_db.RegisterMessage(ItemInfo)

BackpackInfo = _reflection.GeneratedProtocolMessageType('BackpackInfo', (_message.Message,), {
  'DESCRIPTOR' : _BACKPACKINFO,
  '__module__' : 'InventoryMessage_pb2'
  # @@protoc_insertion_point(class_scope:InventoryMessage.BackpackInfo)
  })
_sym_db.RegisterMessage(BackpackInfo)


# @@protoc_insertion_point(module_scope)
