# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ItemMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ItemMessage.proto',
  package='ItemMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11ItemMessage.proto\x12\x0bItemMessage\">\n\x0bItemMessage\x12\x0b\n\x03\x65id\x18\x01 \x01(\x05\x12\x11\n\titem_type\x18\x02 \x01(\x05\x12\x0f\n\x07item_id\x18\x03 \x01(\x05\x62\x06proto3')
)




_ITEMMESSAGE = _descriptor.Descriptor(
  name='ItemMessage',
  full_name='ItemMessage.ItemMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eid', full_name='ItemMessage.ItemMessage.eid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_type', full_name='ItemMessage.ItemMessage.item_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='ItemMessage.ItemMessage.item_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['ItemMessage'] = _ITEMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemMessage = _reflection.GeneratedProtocolMessageType('ItemMessage', (_message.Message,), {
  'DESCRIPTOR' : _ITEMMESSAGE,
  '__module__' : 'ItemMessage_pb2'
  # @@protoc_insertion_point(class_scope:ItemMessage.ItemMessage)
  })
_sym_db.RegisterMessage(ItemMessage)


# @@protoc_insertion_point(module_scope)
