# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto3.proto',
  package='proto_util_converter.testing',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cproto3.proto\x12\x1cproto_util_converter.testing\"\x84\x01\n\rProto3Message\x12J\n\nenum_value\x18\x01 \x01(\x0e\x32\x36.proto_util_converter.testing.Proto3Message.NestedEnum\"\'\n\nNestedEnum\x12\x07\n\x03\x46OO\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\x62\x06proto3')
)



_PROTO3MESSAGE_NESTEDENUM = _descriptor.EnumDescriptor(
  name='NestedEnum',
  full_name='proto_util_converter.testing.Proto3Message.NestedEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAZ', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=140,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_PROTO3MESSAGE_NESTEDENUM)


_PROTO3MESSAGE = _descriptor.Descriptor(
  name='Proto3Message',
  full_name='proto_util_converter.testing.Proto3Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enum_value', full_name='proto_util_converter.testing.Proto3Message.enum_value', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROTO3MESSAGE_NESTEDENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=179,
)

_PROTO3MESSAGE.fields_by_name['enum_value'].enum_type = _PROTO3MESSAGE_NESTEDENUM
_PROTO3MESSAGE_NESTEDENUM.containing_type = _PROTO3MESSAGE
DESCRIPTOR.message_types_by_name['Proto3Message'] = _PROTO3MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proto3Message = _reflection.GeneratedProtocolMessageType('Proto3Message', (_message.Message,), {
  'DESCRIPTOR' : _PROTO3MESSAGE,
  '__module__' : 'proto3_pb2'
  # @@protoc_insertion_point(class_scope:proto_util_converter.testing.Proto3Message)
  })
_sym_db.RegisterMessage(Proto3Message)


# @@protoc_insertion_point(module_scope)
