# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InventoryMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Struct import CommonStruct_pb2 as Struct_dot_CommonStruct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='InventoryMessage.proto',
  package='InventoryMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16InventoryMessage.proto\x12\x10InventoryMessage\x1a\x19Struct/CommonStruct.proto\"*\n\x08ItemInfo\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"d\n\x0cItemTypeInfo\x12)\n\titem_type\x18\x01 \x01(\x0e\x32\x16.CommonStruct.ItemType\x12)\n\x05items\x18\x02 \x03(\x0b\x32\x1a.InventoryMessage.ItemInfo\"\"\n\x13SyncBackpackRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x05\"]\n\x14SyncBackpackResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x35\n\rbackpack_info\x18\x02 \x03(\x0b\x32\x1e.InventoryMessage.ItemTypeInfo*F\n\tproto_ids\x12\x0f\n\x0b\x45MPTY_PROTO\x10\x00\x12\x15\n\x11INVENTORY_SERVICE\x10\x06\x12\x11\n\rSYNC_BACKPACK\x10\x01\x62\x06proto3')
  ,
  dependencies=[Struct_dot_CommonStruct__pb2.DESCRIPTOR,])

_PROTO_IDS = _descriptor.EnumDescriptor(
  name='proto_ids',
  full_name='InventoryMessage.proto_ids',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMPTY_PROTO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVENTORY_SERVICE', index=1, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYNC_BACKPACK', index=2, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=348,
  serialized_end=418,
)
_sym_db.RegisterEnumDescriptor(_PROTO_IDS)

proto_ids = enum_type_wrapper.EnumTypeWrapper(_PROTO_IDS)
EMPTY_PROTO = 0
INVENTORY_SERVICE = 6
SYNC_BACKPACK = 1



_ITEMINFO = _descriptor.Descriptor(
  name='ItemInfo',
  full_name='InventoryMessage.ItemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='InventoryMessage.ItemInfo.item_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='InventoryMessage.ItemInfo.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=113,
)


_ITEMTYPEINFO = _descriptor.Descriptor(
  name='ItemTypeInfo',
  full_name='InventoryMessage.ItemTypeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_type', full_name='InventoryMessage.ItemTypeInfo.item_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='InventoryMessage.ItemTypeInfo.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=215,
)


_SYNCBACKPACKREQUEST = _descriptor.Descriptor(
  name='SyncBackpackRequest',
  full_name='InventoryMessage.SyncBackpackRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='InventoryMessage.SyncBackpackRequest.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=251,
)


_SYNCBACKPACKRESPONSE = _descriptor.Descriptor(
  name='SyncBackpackResponse',
  full_name='InventoryMessage.SyncBackpackResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='InventoryMessage.SyncBackpackResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backpack_info', full_name='InventoryMessage.SyncBackpackResponse.backpack_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=346,
)

_ITEMTYPEINFO.fields_by_name['item_type'].enum_type = Struct_dot_CommonStruct__pb2._ITEMTYPE
_ITEMTYPEINFO.fields_by_name['items'].message_type = _ITEMINFO
_SYNCBACKPACKRESPONSE.fields_by_name['backpack_info'].message_type = _ITEMTYPEINFO
DESCRIPTOR.message_types_by_name['ItemInfo'] = _ITEMINFO
DESCRIPTOR.message_types_by_name['ItemTypeInfo'] = _ITEMTYPEINFO
DESCRIPTOR.message_types_by_name['SyncBackpackRequest'] = _SYNCBACKPACKREQUEST
DESCRIPTOR.message_types_by_name['SyncBackpackResponse'] = _SYNCBACKPACKRESPONSE
DESCRIPTOR.enum_types_by_name['proto_ids'] = _PROTO_IDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemInfo = _reflection.GeneratedProtocolMessageType('ItemInfo', (_message.Message,), {
  'DESCRIPTOR' : _ITEMINFO,
  '__module__' : 'InventoryMessage_pb2'
  # @@protoc_insertion_point(class_scope:InventoryMessage.ItemInfo)
  })
_sym_db.RegisterMessage(ItemInfo)

ItemTypeInfo = _reflection.GeneratedProtocolMessageType('ItemTypeInfo', (_message.Message,), {
  'DESCRIPTOR' : _ITEMTYPEINFO,
  '__module__' : 'InventoryMessage_pb2'
  # @@protoc_insertion_point(class_scope:InventoryMessage.ItemTypeInfo)
  })
_sym_db.RegisterMessage(ItemTypeInfo)

SyncBackpackRequest = _reflection.GeneratedProtocolMessageType('SyncBackpackRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCBACKPACKREQUEST,
  '__module__' : 'InventoryMessage_pb2'
  # @@protoc_insertion_point(class_scope:InventoryMessage.SyncBackpackRequest)
  })
_sym_db.RegisterMessage(SyncBackpackRequest)

SyncBackpackResponse = _reflection.GeneratedProtocolMessageType('SyncBackpackResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNCBACKPACKRESPONSE,
  '__module__' : 'InventoryMessage_pb2'
  # @@protoc_insertion_point(class_scope:InventoryMessage.SyncBackpackResponse)
  })
_sym_db.RegisterMessage(SyncBackpackResponse)


# @@protoc_insertion_point(module_scope)
