// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameMessage {

  /// <summary>Holder for reflection information generated from GameMessage.proto</summary>
  public static partial class GameMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for GameMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHYW1lTWVzc2FnZS5wcm90bxILR2FtZU1lc3NhZ2UaFkludmVudG9yeU1l",
            "c3NhZ2UucHJvdG8aGVN0cnVjdC9Db21tb25TdHJ1Y3QucHJvdG8aF1N0cnVj",
            "dC9JdGVtU3RydWN0LnByb3RvIjwKE1BsYXllck9ubGluZVJlcXVlc3QSCwoD",
            "cmlkGAEgASgFEgsKA2VpZBgCIAEoBRILCgN1aWQYAyABKAUiMwoUUGxheWVy",
            "T25saW5lUmVzcG9uc2USDgoGcmVzdWx0GAEgASgFEgsKA2VpZBgCIAEoBSLF",
            "AgoMUHVsbFJlc3BvbnNlEg4KBnJlc3VsdBgBIAEoBRIsCgdwbGF5ZXJzGAIg",
            "AygLMhsuQ29tbW9uU3RydWN0Lk5ldFBsYXllckRhdGESKgoGcm9ib3RzGAMg",
            "AygLMhouQ29tbW9uU3RydWN0Lk5ldFJvYm90RGF0YRIwCgljb21wdXRlcnMY",
            "BCADKAsyHS5Db21tb25TdHJ1Y3QuTmV0Q29tcHV0ZXJEYXRhEi0KDWFpX2l0",
            "ZW1zX2luZm8YBSADKAsyFi5JdGVtU3RydWN0LkFpSXRlbUluZm8SMwoQZXF1",
            "aXBfaXRlbXNfaW5mbxgGIAMoCzIZLkl0ZW1TdHJ1Y3QuRXF1aXBJdGVtSW5m",
            "bxI1Cg1iYWNrcGFja19pbmZvGAcgAygLMh4uSW52ZW50b3J5TWVzc2FnZS5C",
            "YWNrcGFja0luZm8qSgoJcHJvdG9faWRzEg8KC0VNUFRZX1BST1RPEAASEAoM",
            "R0FNRV9TRVJWSUNFEBASEAoMUExBWUVST05MSU5FEAESCAoEUFVMTBACYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::InventoryMessage.InventoryMessageReflection.Descriptor, global::CommonStruct.CommonStructReflection.Descriptor, global::ItemStruct.ItemStructReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameMessage.proto_ids), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.PlayerOnlineRequest), global::GameMessage.PlayerOnlineRequest.Parser, new[]{ "Rid", "Eid", "Uid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.PlayerOnlineResponse), global::GameMessage.PlayerOnlineResponse.Parser, new[]{ "Result", "Eid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessage.PullResponse), global::GameMessage.PullResponse.Parser, new[]{ "Result", "Players", "Robots", "Computers", "AiItemsInfo", "EquipItemsInfo", "BackpackInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum proto_ids {
    [pbr::OriginalName("EMPTY_PROTO")] EmptyProto = 0,
    /// <summary>
    /// service id
    /// </summary>
    [pbr::OriginalName("GAME_SERVICE")] GameService = 16,
    /// <summary>
    /// command id
    /// </summary>
    [pbr::OriginalName("PLAYERONLINE")] Playeronline = 1,
    [pbr::OriginalName("PULL")] Pull = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// sender
  /// </summary>
  public sealed partial class PlayerOnlineRequest : pb::IMessage<PlayerOnlineRequest> {
    private static readonly pb::MessageParser<PlayerOnlineRequest> _parser = new pb::MessageParser<PlayerOnlineRequest>(() => new PlayerOnlineRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerOnlineRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.GameMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerOnlineRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerOnlineRequest(PlayerOnlineRequest other) : this() {
      rid_ = other.rid_;
      eid_ = other.eid_;
      uid_ = other.uid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerOnlineRequest Clone() {
      return new PlayerOnlineRequest(this);
    }

    /// <summary>Field number for the "rid" field.</summary>
    public const int RidFieldNumber = 1;
    private int rid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rid {
      get { return rid_; }
      set {
        rid_ = value;
      }
    }

    /// <summary>Field number for the "eid" field.</summary>
    public const int EidFieldNumber = 2;
    private int eid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Eid {
      get { return eid_; }
      set {
        eid_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 3;
    private int uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerOnlineRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerOnlineRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Rid != other.Rid) return false;
      if (Eid != other.Eid) return false;
      if (Uid != other.Uid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Rid != 0) hash ^= Rid.GetHashCode();
      if (Eid != 0) hash ^= Eid.GetHashCode();
      if (Uid != 0) hash ^= Uid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Rid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Rid);
      }
      if (Eid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Eid);
      }
      if (Uid != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Uid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Rid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rid);
      }
      if (Eid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Eid);
      }
      if (Uid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Uid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerOnlineRequest other) {
      if (other == null) {
        return;
      }
      if (other.Rid != 0) {
        Rid = other.Rid;
      }
      if (other.Eid != 0) {
        Eid = other.Eid;
      }
      if (other.Uid != 0) {
        Uid = other.Uid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Rid = input.ReadInt32();
            break;
          }
          case 16: {
            Eid = input.ReadInt32();
            break;
          }
          case 24: {
            Uid = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerOnlineResponse : pb::IMessage<PlayerOnlineResponse> {
    private static readonly pb::MessageParser<PlayerOnlineResponse> _parser = new pb::MessageParser<PlayerOnlineResponse>(() => new PlayerOnlineResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerOnlineResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.GameMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerOnlineResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerOnlineResponse(PlayerOnlineResponse other) : this() {
      result_ = other.result_;
      eid_ = other.eid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerOnlineResponse Clone() {
      return new PlayerOnlineResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "eid" field.</summary>
    public const int EidFieldNumber = 2;
    private int eid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Eid {
      get { return eid_; }
      set {
        eid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerOnlineResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerOnlineResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (Eid != other.Eid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (Eid != 0) hash ^= Eid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (Eid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Eid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (Eid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Eid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerOnlineResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.Eid != 0) {
        Eid = other.Eid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
          case 16: {
            Eid = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// sender
  /// </summary>
  public sealed partial class PullResponse : pb::IMessage<PullResponse> {
    private static readonly pb::MessageParser<PullResponse> _parser = new pb::MessageParser<PullResponse>(() => new PullResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PullResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessage.GameMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullResponse(PullResponse other) : this() {
      result_ = other.result_;
      players_ = other.players_.Clone();
      robots_ = other.robots_.Clone();
      computers_ = other.computers_.Clone();
      aiItemsInfo_ = other.aiItemsInfo_.Clone();
      equipItemsInfo_ = other.equipItemsInfo_.Clone();
      backpackInfo_ = other.backpackInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullResponse Clone() {
      return new PullResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CommonStruct.NetPlayerData> _repeated_players_codec
        = pb::FieldCodec.ForMessage(18, global::CommonStruct.NetPlayerData.Parser);
    private readonly pbc::RepeatedField<global::CommonStruct.NetPlayerData> players_ = new pbc::RepeatedField<global::CommonStruct.NetPlayerData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CommonStruct.NetPlayerData> Players {
      get { return players_; }
    }

    /// <summary>Field number for the "robots" field.</summary>
    public const int RobotsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CommonStruct.NetRobotData> _repeated_robots_codec
        = pb::FieldCodec.ForMessage(26, global::CommonStruct.NetRobotData.Parser);
    private readonly pbc::RepeatedField<global::CommonStruct.NetRobotData> robots_ = new pbc::RepeatedField<global::CommonStruct.NetRobotData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CommonStruct.NetRobotData> Robots {
      get { return robots_; }
    }

    /// <summary>Field number for the "computers" field.</summary>
    public const int ComputersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::CommonStruct.NetComputerData> _repeated_computers_codec
        = pb::FieldCodec.ForMessage(34, global::CommonStruct.NetComputerData.Parser);
    private readonly pbc::RepeatedField<global::CommonStruct.NetComputerData> computers_ = new pbc::RepeatedField<global::CommonStruct.NetComputerData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CommonStruct.NetComputerData> Computers {
      get { return computers_; }
    }

    /// <summary>Field number for the "ai_items_info" field.</summary>
    public const int AiItemsInfoFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ItemStruct.AiItemInfo> _repeated_aiItemsInfo_codec
        = pb::FieldCodec.ForMessage(42, global::ItemStruct.AiItemInfo.Parser);
    private readonly pbc::RepeatedField<global::ItemStruct.AiItemInfo> aiItemsInfo_ = new pbc::RepeatedField<global::ItemStruct.AiItemInfo>();
    /// <summary>
    /// 推送所有种类物品的基本信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ItemStruct.AiItemInfo> AiItemsInfo {
      get { return aiItemsInfo_; }
    }

    /// <summary>Field number for the "equip_items_info" field.</summary>
    public const int EquipItemsInfoFieldNumber = 6;
    private static readonly pb::FieldCodec<global::ItemStruct.EquipItemInfo> _repeated_equipItemsInfo_codec
        = pb::FieldCodec.ForMessage(50, global::ItemStruct.EquipItemInfo.Parser);
    private readonly pbc::RepeatedField<global::ItemStruct.EquipItemInfo> equipItemsInfo_ = new pbc::RepeatedField<global::ItemStruct.EquipItemInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ItemStruct.EquipItemInfo> EquipItemsInfo {
      get { return equipItemsInfo_; }
    }

    /// <summary>Field number for the "backpack_info" field.</summary>
    public const int BackpackInfoFieldNumber = 7;
    private static readonly pb::FieldCodec<global::InventoryMessage.BackpackInfo> _repeated_backpackInfo_codec
        = pb::FieldCodec.ForMessage(58, global::InventoryMessage.BackpackInfo.Parser);
    private readonly pbc::RepeatedField<global::InventoryMessage.BackpackInfo> backpackInfo_ = new pbc::RepeatedField<global::InventoryMessage.BackpackInfo>();
    /// <summary>
    /// 同步背包信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::InventoryMessage.BackpackInfo> BackpackInfo {
      get { return backpackInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PullResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PullResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!players_.Equals(other.players_)) return false;
      if(!robots_.Equals(other.robots_)) return false;
      if(!computers_.Equals(other.computers_)) return false;
      if(!aiItemsInfo_.Equals(other.aiItemsInfo_)) return false;
      if(!equipItemsInfo_.Equals(other.equipItemsInfo_)) return false;
      if(!backpackInfo_.Equals(other.backpackInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      hash ^= players_.GetHashCode();
      hash ^= robots_.GetHashCode();
      hash ^= computers_.GetHashCode();
      hash ^= aiItemsInfo_.GetHashCode();
      hash ^= equipItemsInfo_.GetHashCode();
      hash ^= backpackInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      players_.WriteTo(output, _repeated_players_codec);
      robots_.WriteTo(output, _repeated_robots_codec);
      computers_.WriteTo(output, _repeated_computers_codec);
      aiItemsInfo_.WriteTo(output, _repeated_aiItemsInfo_codec);
      equipItemsInfo_.WriteTo(output, _repeated_equipItemsInfo_codec);
      backpackInfo_.WriteTo(output, _repeated_backpackInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      size += players_.CalculateSize(_repeated_players_codec);
      size += robots_.CalculateSize(_repeated_robots_codec);
      size += computers_.CalculateSize(_repeated_computers_codec);
      size += aiItemsInfo_.CalculateSize(_repeated_aiItemsInfo_codec);
      size += equipItemsInfo_.CalculateSize(_repeated_equipItemsInfo_codec);
      size += backpackInfo_.CalculateSize(_repeated_backpackInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PullResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      players_.Add(other.players_);
      robots_.Add(other.robots_);
      computers_.Add(other.computers_);
      aiItemsInfo_.Add(other.aiItemsInfo_);
      equipItemsInfo_.Add(other.equipItemsInfo_);
      backpackInfo_.Add(other.backpackInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
          case 18: {
            players_.AddEntriesFrom(input, _repeated_players_codec);
            break;
          }
          case 26: {
            robots_.AddEntriesFrom(input, _repeated_robots_codec);
            break;
          }
          case 34: {
            computers_.AddEntriesFrom(input, _repeated_computers_codec);
            break;
          }
          case 42: {
            aiItemsInfo_.AddEntriesFrom(input, _repeated_aiItemsInfo_codec);
            break;
          }
          case 50: {
            equipItemsInfo_.AddEntriesFrom(input, _repeated_equipItemsInfo_codec);
            break;
          }
          case 58: {
            backpackInfo_.AddEntriesFrom(input, _repeated_backpackInfo_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
