# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Demo.proto',
  package='Demo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nDemo.proto\x12\x04\x44\x65mo\"=\n\x0b\x44\x65moRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"*\n\x0c\x44\x65moResponse\x12\x0b\n\x03uid\x18\x01 \x01(\x05\x12\r\n\x05is_ok\x18\x02 \x01(\x08\x62\x06proto3')
)




_DEMOREQUEST = _descriptor.Descriptor(
  name='DemoRequest',
  full_name='Demo.DemoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Demo.DemoRequest.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account', full_name='Demo.DemoRequest.account', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='Demo.DemoRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=81,
)


_DEMORESPONSE = _descriptor.Descriptor(
  name='DemoResponse',
  full_name='Demo.DemoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Demo.DemoResponse.uid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_ok', full_name='Demo.DemoResponse.is_ok', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['DemoRequest'] = _DEMOREQUEST
DESCRIPTOR.message_types_by_name['DemoResponse'] = _DEMORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DemoRequest = _reflection.GeneratedProtocolMessageType('DemoRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEMOREQUEST,
  '__module__' : 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:Demo.DemoRequest)
  })
_sym_db.RegisterMessage(DemoRequest)

DemoResponse = _reflection.GeneratedProtocolMessageType('DemoResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEMORESPONSE,
  '__module__' : 'Demo_pb2'
  # @@protoc_insertion_point(class_scope:Demo.DemoResponse)
  })
_sym_db.RegisterMessage(DemoResponse)


# @@protoc_insertion_point(module_scope)
